# Generated by Django 4.1.6 on 2023-10-26 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.order.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0002_alter_cart_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        default=ecommerce.order.models.OrderStatus["PENDING"],
                        max_length=20,
                    ),
                ),
                ("items", models.ManyToManyField(to="cart.cart")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
