# Generated by Django 4.1.6 on 2023-11-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("CONFIRMED", "confirmed"),
                    ("REJECTED", "rejected"),
                    ("DELIVERED", "delivered"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
