# Generated by Django 4.1.6 on 2023-11-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
