# Generated by Django 4.1.6 on 2024-01-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(default="", max_length=3000)),
            ],
        ),
    ]
