# Generated by Django 4.1.6 on 2023-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(blank=True, to="product.productimage"),
        ),
    ]
