# Generated by Django 4.1.6 on 2024-01-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_is_active_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
