# Generated by Django 4.1.6 on 2023-10-07 16:05

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=20, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 10, 7, 16, 5, 10, 329220, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 10, 7, 16, 5, 10, 329339, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("STAFF", "Staff"),
                            ("CUSTOMER", "Customer"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
