# Generated by Django 4.1.6 on 2023-11-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="salt",
            field=models.CharField(default="g9AMTk4uNoBp", max_length=12),
        ),
    ]
