# Generated by Django 4.2.1 on 2024-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="salt",
            field=models.CharField(default="3NsXpjlfZBT9", max_length=12),
        ),
    ]
