# Generated by Django 4.1.6 on 2023-11-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="salt",
            field=models.CharField(default="G0mdUlHiFxTb", max_length=12),
        ),
    ]
