# Generated by Django 4.1.6 on 2024-01-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_salt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="salt",
            field=models.CharField(default="wHpjd1izPJl5", max_length=12),
        ),
    ]
