# Generated by Django 4.1.6 on 2023-10-07 16:53

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 7, 16, 53, 16, 562688, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 7, 16, 53, 16, 562822, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
